language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
 - rabbitmq

before_install:
 - sudo rabbitmq-plugins enable rabbitmq_management
 - sudo rabbitmqctl add_user test test
 - sudo rabbitmqctl set_user_tags test administrator
 - sudo rabbitmqctl set_permissions -p / test \".*\" \".*\" \".*\"
 - sudo rabbitmq-plugins enable rabbitmq_shovel
 - chmod +x tests/test_pyrabbit.py

install:
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install -r requirements3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt; fi
  - cd tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then python3 test_pyrabbit.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python test_pyrabbit.py; fi
